### PR TITLE
TgWebValid is connected

### PR DESCRIPTION
**Pull request by CrazyTapok-bit**
Hello

In this pull request, a soft connection of the [TgWebValid](https://github.com/CrazyTapok-bit/tgWebValid) package is made. This means that at this stage 100% of the backward compatibility of the project is preserved. That is, it can be used exactly as before.

This was done in order to lay the foundation for the future improvement of this project and expansion of its functionality. Namely, add the ability to check [Telegram WebApp](https://core.telegram.org/bots/webapps) users. And it will be done quite simply, because the entire implementation of the check is already in the connected library.

In addition, this library has all the necessary tests to guarantee its stability and correct operation.

Also note that I added a section of scripts in the composer.json file. This was done for the convenience of running tests, now it is easy to do with the `composer test` command

I hope you will accept my contribution to your project and allow you to make it even better in the future

### CODE REVIEW

**Comment by CrazyTapok-bit** [comment]
@pschocke Do you know why Scrutinizer checks project dependencies and how to fix it?

**Comment by CrazyTapok-bit** [comment]
@pschocke hi. Are we continuing the development of your library?

**Comment by pschocke** [comment]
Hey, sorry for the late reply. To be frank I don’t see any advantage adding your package. 

This package was meant to be lightweight. 

Adding your package abstracts the logic deeper and puts my package in a sort of wrapper functionality. This comes with the major downside that I am dependent on your package. If I e.g. want to update the php version I need your package to be updated as well. 

So thank you for your work, but I do have no plans on merging this. 

Stay safe!

**Comment by CrazyTapok-bit** [comment]
Glad to hear from you. 😊

Like any other project, you encounter opportunities and obstacles along the way. That's why I understand your fears and concerns, but I assure you that you worry in vain. 😌

The library is fantastic and genuinely user-friendly. Most importantly, it provides you with numerous opportunities to take your project to a new level, and it does so very quickly and easily. I am confident that this improvement would have a positive impact on your project, making it even more popular and recognizable. You would be able to work not only with the Telegram Login Widget and Telegram Web App but also with various bots simultaneously, all within one project. 🚀

Of course, I'll be sorry that you didn't seize the chance to enhance your project right now, but I hope that we'll have the opportunity to collaborate in the future. 😊🤝

**Pull request closed without merging**
